# Generated by Django 4.2.2 on 2023-06-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryattribute',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
